
#Eureka client configurations
eureka:
  instance:
    prefer-ip-address: true
  
  client:
    fetch-registry: true
    register-with-eureka: true
    
    #defualt URL
    #it will take this url as default url to register this userService
    service-url:
      defaultZone: http://localhost:8761/eureka
